services:

  brothership-backend:
    container_name: brothership-backend
    build: ./brothership-backend
    restart: unless-stopped
    working_dir: '/app'
    # entrypoint: ['sh', './bin/run.sh']
    tty: true
    environment:
      BACKEND_TARGET_PORT: ${BACKEND_TARGET_PORT}
    ports:
      - '${BACKEND_PUBLISHED_PORT}:${BACKEND_TARGET_PORT}'
    volumes:
      - ./brothership-backend:/app
